#include<stdio.h>


int main()
{
    
	FILE *ptr = NULL;		//	FILE ->   predefined struct
							//	ptr  ->	  Ability to hold address of a file

	//	File address is generated by "FILE OPERATION FUNCTIONS" e.g. fopen( file_name, mode )


	return 0;
}

//	FILE STORED IN SECONDARY MEMORY IS FETCHED IN RAM

//	WE NEED TO POINT TO THE FILE VIA FILE POINTER

//	FILE TYPES:	
//		1.	TEXT FILE
//		2.	BINARY FILE

//	FILE is the struct under "stdio.h" that defines the file of both types mentioned above.

